#nmScan Yaml config
fofa:
  FOFA_EMAIL: xxxx@xxxx.com
  FOFA_KEY: xxxxxxxxxxxxxxx
  FOFA_SEARCH_SIZE: 2000  #fafa一次搜索返回的数量
scan:
  PortOpenCountLimit: 100 #可能防火墙过滤原因导致开放端口超过多少个,不对此IP结果进行导出
  NMAPsV: false #是否进行nmap -sV 端口服务版本探测